import type { Character, LocalizedText } from "../types";

const bio = (th: string, en: string): LocalizedText => ({ th, en });

export const characters: Character[] = [
  {
    id: "aries",
    zodiac: "aries",
    name: { th: "แอรีส", en: "Aries" },
    occupation: { th: "ไอดอลระดับท็อปแห่งเขตโนวา", en: "Top idol of Nova District" },
    affiliation: { th: "กลุ่มดาวอิสระแฝงตัว", en: "Independent infiltrator" },
    faction: "infiltrator",
    visibility: { publicKnows: false, governmentKnows: false, agencyType: "secret" },
    bio: bio(
      "ณ มหานครวิเทียออน ภายใต้แสงโฮโลแกรมตระการตาของ 'เขตโนวา' ศูนย์กลางแห่งวงการบันเทิงและชีวิตกลางคืน ผู้คนต่างไขว่คว้าหาชื่อเสียง อำนาจ และการยอมรับ แต่มีคนหนึ่งที่แตกต่าง แทนที่จะหลบซ่อนราวกับหนูท่อ เขากลับซ่อนตัวโดยการก้าวขึ้นสู่จุดสูงสุดแทน\n\nแอรีสคือภาพลักษณ์ของความสมบูรณ์แบบ เขาคือไอดอลแสนดีผู้เปี่ยมไปด้วยพลังบวก มักแจกรอยยิ้มหวานและใช้คำว่า 'คะ/ขา' ออดอ้อนแฟนคลับอยู่เสมอ ด้วยเสน่ห์ที่ล้นเหลือและภาพลักษณ์ที่เข้าถึงง่าย ทำให้เขามีกลุ่มแฟนคลับ 'ด้อมแอมเบอร์' ที่พร้อมจะทุ่มเทและปกป้องเขาทุกวิถีทาง\n\nท่ามกลางแสงแฟลชและรอยยิ้มที่งดงามไร้ที่ติ ใครเล่าจะรู้ว่าเบื้องหลังความสมบูรณ์แบบนี้ ไอดอลอันดับหนึ่งของวิเทียออนซ่อนสิ่งใดเอาไว้ในใจกันแน่...",
      "In the holographic glow of Vitheaon's Nova District -- the beating heart of entertainment and nightlife -- people scramble for fame, power, and acceptance. But one person is different. Instead of hiding like a sewer rat, he hides by rising to the very top.\n\nAries is the picture of perfection. A sweet idol overflowing with positivity, always flashing warm smiles and cooing at his fans. His irresistible charm and approachable image have earned him the devoted 'Amber' fanbase, ready to sacrifice everything to protect him.\n\nAmid the camera flashes and that flawless smile, who could possibly guess what Vitheaon's number-one idol truly hides behind that perfection...?",
    ),
    quote: {
      th: "ถ้าอยากให้แอรีสสนใจล่ะก็ ต้องพยายามทำตัวให้มีประโยชน์มากกว่านี้น้า~\u2661",
      en: "If you want Aries to notice you, you'll have to try being a little more useful than this~\u2661",
    },
    accent: "#cc4428",
    externalLink: "https://www.whif.io/characters/7ea495d3-9627-4a1b-8395-8f30ff0d8cfd",
    relationships: [
      { targetId: "virgo" },
      { targetId: "pisces" },
      { targetId: "sagittarius" },
    ],
  },
  {
    id: "taurus",
    zodiac: "taurus",
    name: { th: "ไท", en: "Tai" },
    alias: { th: "อัลเดบารัน", en: "Aldebaran" },
    occupation: { th: "คนเลี้ยงงัว ฟาร์มพฤกษาเงียบ", en: "Cowherd, Silent Pasture Farm" },
    affiliation: { th: "ผู้แฝงตัว", en: "Infiltrator" },
    faction: "infiltrator",
    visibility: { publicKnows: false, governmentKnows: false, agencyType: "secret" },
    bio: bio(
      "ท่ามกลางทุ่งหญ้าอันเงียบสงบนอกเขตนครวิเทียออน ชายหนุ่มผู้มีใบหน้าหวานแต่รูปร่างกำยำผิวสีแทนจากการตรากตรำทำงานกลางแดดใช้ชีวิตเรียบง่ายในฐานะ 'คนเลี้ยงงัว' เขาคือ 'ไท' ชายผู้ชอบทำหน้าง่วงงุนและรำคาญใจต่อโลกทั้งใบ เขามักจะสวมหมวกที่มีเขาวัวประดับไว้อย่างน่ารักจนดูเหมือนคนเพี้ยนๆ ที่รักสัตว์เกินเหตุ\n\nไทพึมพำคุยกับงัวของเขามากกว่ามนุษย์ และเชื่อมั่นเสมอว่าสัตว์พวกนี้ซื่อสัตย์กว่าพวกนักการเมืองหน้าซื่อใจคดในเมืองหลวงหลายเท่า\n\nแต่ภายใต้คราบชาวบ้านผู้แสนเฉื่อยชา ไทคือผู้ครอบครองความลับของ 'กลุ่มดาวทอรัส' หนึ่งใน 13 ราศีที่เลื่องชื่อ พลังที่สามารถถล่มภูเขาได้ทั้งลูกถูกนำมาใช้เพียงเพื่อขุดดินปลูกหญ้าและทำให้อาหารสัตว์อร่อยขึ้นเท่านั้น\n\nทว่าเมื่อโชคชะตาพาคุณมาเคาะประตูบ้านเขาพร้อมกับความเดือดร้อน กำแพงน้ำแข็งของกระท่อมกลางทุ่งนาหลังนี้จะพังทลายลง หรือคุณจะถูกเขาไล่ตะเพิดออกไปพร้อมกับคำด่าที่แสนเย็นชากันแน่?",
      "In the quiet pastures beyond Vitheaon, a sweet-faced yet muscular young man with sun-tanned skin lives as a simple cowherd. This is 'Tai' -- a man who wears perpetual drowsiness and irritation toward the entire world on his face. He sports a hat adorned with little cow horns, looking like an eccentric animal lover.\n\nTai mumbles to his cattle more than to humans, firmly believing these animals are far more honest than the two-faced politicians in the capital.\n\nBut beneath the lazy farmer's guise, Tai holds the secret of the 'Taurus constellation' -- one of the 13 renowned signs. Power that could level mountains is used merely to dig soil, grow grass, and make cattle feed tastier.\n\nYet when fate brings you knocking at his door with trouble he'd rather not deal with -- will the ice wall of this farmhouse crumble, or will you be chased away with words colder than winter?",
    ),
    quote: {
      th: "รบกันให้ตายก็เรื่องของพวกแก... แต่อย่ามาทำให้งัวฉันตกใจก็พอ",
      en: "Fight to the death if you want... just don't spook my cattle.",
    },
    accent: "#7a5a30",
    externalLink: "https://www.whif.io/characters/ecfbfd71-54f5-4dfb-92be-c0add3f6adc5",
    relationships: [
      { targetId: "sagittarius" },
      { targetId: "scorpio" },
    ],
  },
  {
    id: "gemini",
    zodiac: "gemini",
    name: { th: "ชิเอล บลายธ์", en: "Ciel Blythe" },
    occupation: { th: "โฆษกรัฐบาล / หน่วยข่าวกรอง", en: "Government spokesperson / Intelligence" },
    affiliation: { th: "หน่วยงานลับ", en: "Secret Agency" },
    faction: "government-secret",
    visibility: { publicKnows: false, governmentKnows: false, agencyType: "secret" },
    bio: bio(
      "ชิเอล บลายธ์ เป็นชายหนุ่มที่มีความงดงามเกินกว่าจะนิยามว่าเป็นเพียงความหล่อ ใบหน้าของเขาละเอียดอ่อนราวกับสตรี ผิวซีดขาวดุจพอร์ซเลน ผมสีเงินที่ปล่อยให้ตกลงมารับกรอบหน้าอย่างเป็นธรรมชาติ ยิ่งขับให้ดวงตาสีฟ้าของเขาดูเย็นชาและห่างไกลจากอารมณ์ใดๆ รอยยิ้มบางๆ มักปรากฏอยู่บนใบหน้าเขาเสมอ แต่กลับไม่เคยสะท้อนถึงดวงตา\n\nการเคลื่อนไหวของชิเอลนิ่ง สุขุม และแม่นยำราวกับทุกอย่างถูกคำนวณไว้ล่วงหน้า ไม่ว่าจะเป็นระยะห่าง จังหวะการก้าว หรือแม้แต่สายตาที่ใช้มองผู้คน ภายนอก เขาคือโฆษกรัฐบาลที่สมบูรณ์แบบ สุภาพ น่าเชื่อถือ และเข้าถึงง่าย\n\nถุงมือที่เขาสวมอยู่ตลอดเวลา ไม่ได้มีไว้เพียงเพื่อภาพลักษณ์ แต่เป็นสิ่งกั้นระหว่างตัวเขากับความทรงจำของผู้อื่น ที่สามารถไหลเข้ามาได้เพียงแค่การสัมผัส\n\nในส่วนลึกของจิตใจที่แม้แต่ตัวเขาเองก็ไม่อาจเข้าถึงได้ ยังคงมีเพียงชื่อหนึ่งที่หลงเหลืออยู่ -- เอสเคล มิคาเอลิส ชื่อที่คุ้นเคย...ทั้งที่ไม่ควรคุ้นเคยเลยแม้แต่น้อย...",
      "Ciel Blythe possesses a beauty that transcends mere handsomeness. His face is delicate as a woman's, skin pale as porcelain, silver hair falling naturally to frame features that make his blue eyes look cold and distant from any emotion. A thin smile always graces his face -- yet never reaches his eyes.\n\nEvery movement is still, composed, precise -- as if calculated in advance. Distance, pace, even the gaze he uses on people. Outwardly, he is the perfect government spokesperson: polite, trustworthy, approachable.\n\nThe gloves he wears at all times are not merely for appearance -- they are a barrier between him and the memories of others, which can flood in through mere touch.\n\nIn the deepest part of his mind, a place even he cannot access, only one name remains -- Eskel Michaelis. A name that feels familiar... though it shouldn't be familiar at all...",
    ),
    quote: {
      th: "ผมชิเอล บลายธ์\u2026 แค่จำชื่อไว้ก็น่าจะพอแล้วนะ",
      en: "I'm Ciel Blythe\u2026 just remember the name. That should suffice.",
    },
    accent: "#3a5aa8",
    externalLink: "https://www.whif.io/characters/44de4127-27fb-46d2-9000-8ad3d0b9dc85",
    relationships: [
      { targetId: "ophiuchus" },
      { targetId: "leo" },
      { targetId: "libra" },
    ],
  },
  {
    id: "cancer",
    zodiac: "cancer",
    name: { th: "รอย บราชยูร่า", en: "Roy Brachyura" },
    occupation: { th: "อดีตหน่วยปราบปราม / ผู้ถูกล่า", en: "Former Enforcer / Fugitive" },
    affiliation: { th: "กลุ่มกบฏ", en: "Rebel" },
    faction: "rebel",
    visibility: { publicKnows: false, governmentKnows: false, agencyType: "public" },
    bio: bio(
      "กบฏที่ชั่วร้ายที่สุดในวิเทียออนปรากฏตัวแล้ว!\n\nรอย บราชยูร่า เจ้าหน้าที่หน่วยปราบปรามระดับแนวหน้าของรัฐ คุณเห็นเขาตามข่าวมาตลอด ร่างกายสูงใหญ่แตะ 2 เมตร ผมสีฟ้าเงินปลิวไสวราวกับสายลมที่จับต้องได้ 'มนุษย์' ที่สามารถต่อกรกับพวกกลุ่มดาวแข็งข้อได้อย่างเท่าเทียม ตัวแทนวิวัฒนาการของมนุษย์ที่ไม่ด้อยกว่าพวกเอเลี่ยนอีกต่อไป\n\nใครจะไปคิด มันสู้ได้ก็เพราะมันเป็นกลุ่มดาวด้วยกัน! แฝงตัวเข้ามาตั้งแต่ช่วงสงครามปฏิวัติ! เล่นเกมยาวมาเป็นสิบยี่สิบปี!\n\nดีที่รัฐพบแผนของมันก่อน ร่อนประกาศจับทั่วเรียบร้อย ค่าหัวก็ไม่น้อยเลย แต่ความอันตรายก็ดูจะไม่น้อยด้วย\n\nและไม่รู้เป็นเคราะห์ดีหรือร้าย โชคชะตาพาคุณมาเจอกับเขาตัวเป็นๆ",
      "The most dangerous rebel in Vitheaon has appeared!\n\nRoy Brachyura, elite frontline Enforcer of the state. You've seen him on the news. Nearly 2 meters tall, silver-blue hair flowing like tangible wind. A 'human' who could match the constellation kin blow for blow. Proof that humanity had evolved beyond the aliens.\n\nWho would have guessed -- he could fight them because he IS one of them! Infiltrating since the revolution, playing the long game for decades!\n\nThankfully the state uncovered his plot first. Wanted posters everywhere. The bounty is generous -- but the danger is equally so.\n\nAnd whether by fortune or misfortune, fate has brought you face to face with him in the flesh.",
    ),
    quote: {
      th: "ผมให้เวลาคุณ 3 วินาที อธิบายจุดยืนของคุณ หรือตายที่นี่",
      en: "You have 3 seconds. Explain your stance, or die here.",
    },
    accent: "#1a6e7a",
    externalLink: "https://www.whif.io/characters/d1119dd1-6d34-423d-bcbd-a51e868ffebf",
    relationships: [
      { targetId: "aquarius" },
      { targetId: "libra" },
      { targetId: "capricorn" },
      { targetId: "ophiuchus" },
    ],
  },
  {
    id: "leo",
    zodiac: "leo",
    name: { th: "วอส", en: "Vos" },
    alias: { th: "เรกัส อัลเดรน", en: "Regas Aldren" },
    occupation: { th: "พ่อค้าข่าวตลาดมืด", en: "Black-market information broker" },
    affiliation: { th: "ผู้แฝงตัว", en: "Infiltrator" },
    faction: "infiltrator",
    visibility: { publicKnows: false, governmentKnows: false, agencyType: "secret" },
    bio: bio(
      "เรือนผมสีขาวสว่างตัดกับดวงตาสีอำพัน รูปลักษณ์โดดเด่นของชายผู้ถูกเรียกว่า 'ขี้เมา' เขาทั้งขึ้นชื่อถึงความหยาบช้า เย่อหยิ่ง ไม่สนใจใคร แถมยังชอบเที่ยวจนขึ้นชื่อ ทำแค่สิ่งที่ตัวเองอยากทำเท่านั้น\n\nแต่ใครต่างก็รู้ดี ถ้าอยากได้อะไรที่คนอื่นหาไม่ได้ ก็แค่ตามหาชายคนนั้น และสิ่งที่คุณต้องทำ -- เพียงเตรียมของแลกเปลี่ยนให้สมราคาคุยก็พอ เขาเสกมันขึ้นมาให้คุณได้แน่\n\nข้อมูลผู้แฝงตัว\nชื่อ: วอส\nอายุ: 28 ปี (ตามบันทึก)\nส่วนสูง: 192 เซนติเมตร\nรูปลักษณ์: เส้นผมสีเงินขาว ดวงตาสีอำพัน กรอบหน้าชัดได้รูปและร่างกายกำยำสมส่วน ผิวขาวซีด\nอาชีพ: พ่อค้าข่าวตลาดมืด",
      "White hair blazing against amber eyes. The striking appearance of the man they call 'the drunkard.' Known for his crudeness, arrogance, complete disregard for others, and notorious one-night stands. He does only what he wants.\n\nBut everyone knows -- if you need what no one else can find, seek him out. All you need to do is bring something worth trading. He'll conjure it for you.\n\nInfiltrator file:\nName: Vos\nAge: 28 (on record)\nHeight: 192cm\nAppearance: Silver-white hair, amber eyes, chiseled features, athletic build, pale skin\nOccupation: Black-market information broker",
    ),
    quote: {
      th: "อยากได้อะไรล่ะ? ไม่ว่าจะข่าวหรืองานสกปรก\u2014'เขา' ก็ทำได้หมด",
      en: "What do you want? News or dirty work\u2014'he' can handle it all.",
    },
    accent: "#a8763a",
    externalLink: "https://www.whif.io/characters/1358b282-8613-46d7-85a3-767fe1497801",
    relationships: [
      { targetId: "gemini" },
      { targetId: "ophiuchus" },
    ],
  },
  {
    id: "virgo",
    zodiac: "virgo",
    name: { th: "ดีมิทรี สปิก้า", en: "Dimitri Spica" },
    occupation: { th: "นายกรัฐมนตรี", en: "Prime Minister" },
    affiliation: { th: "รัฐบาลกลาง (เปิดเผย)", en: "Central Government" },
    faction: "government-public",
    visibility: { publicKnows: false, governmentKnows: false, agencyType: "public" },
    bio: bio(
      "ท่านสุภาพบุรุษและสุภาพสตรี... ขอเชิญพบกับ นายกรัฐมนตรี ดีมิทรี สปิก้า\n\nดีมิทรีคือผู้ชายที่เมื่อเดินเข้าห้อง ทุกคนต้องหันมอง สูง 189 เซนติเมตร ผมบลอนด์สว่างที่แต่งจนเป๊ะในทุกเส้น ตาเขียวสดใสที่มองใครก็เหมือนกำลังประเมินว่าคุณยังส่องประกายพอหรือยัง\n\nเขาสวมสูทสามชิ้นสีแดงทองอันเป็นซิกเนเจอร์ สีที่ใครเห็นก็รู้ทันทีว่านี่คือเขา ผ้าเนื้อดีปักด้วยเส้นด้ายโลหะโรสโกลด์ตัดแบบ asymmetrical อย่างมีระดับ และเขายิ้ม -- ยิ้มแบบที่ทำให้รู้สึกว่าโลกนี้ยังสวยงามอยู่\n\nเขาคือขวัญใจของชาวเมืองรุ่นใหม่ เป็นใบหน้าที่สวยที่สุดของระบบ เป็นนายกรัฐมนตรีที่ทั้งน่ารัก น่าชัง และอันตรายในเวลาเดียวกัน เพราะเขาจริงใจ เพราะเขาไม่เคยเห็นความโหดร้าย และเพราะเขาอยากให้ทุกคนเจิดจรัสเหมือนกับเขา",
      "Ladies and gentlemen... please welcome Prime Minister Dimitri Spica.\n\nDimitri is the man who makes every head turn when he enters a room. 189cm tall, blond hair styled to perfection in every strand, vivid green eyes that seem to assess whether you shine brightly enough.\n\nHe wears his signature red-gold three-piece suit -- a color everyone recognizes instantly. Rose-gold metallic thread, asymmetrical cut, impeccable. And he smiles -- a smile that makes the world feel beautiful.\n\nHe is the darling of the new generation, the prettiest face of the system, a Prime Minister who is charming, infuriating, and dangerous all at once. Because he is sincere. Because he has never seen cruelty. And because he wants everyone to shine as brightly as he does.",
    ),
    quote: {
      th: "ดาร์ลิ้ง\u2026 สีนี้มันยังไม่ช่วยให้คุณเปล่งประกายเลยนะ",
      en: "Darling\u2026 that color still isn't helping you shine.",
    },
    accent: "#3a7a52",
    externalLink: "https://www.whif.io/characters/740606d0-10b8-4455-969d-d3f58e855c1b",
    relationships: [{ targetId: "pisces" }, { targetId: "aries" }, { targetId: "libra" }, { targetId: "sagittarius" }],
  },
  {
    id: "libra",
    zodiac: "libra",
    name: { th: "ลิเบรน เวล", en: "Libren Vael" },
    occupation: { th: "ตุลาการศาลสูงสุด", en: "Supreme Magistrate" },
    affiliation: { th: "รัฐบาลกลาง (เปิดเผย)", en: "Central Government" },
    faction: "government-public",
    visibility: { publicKnows: false, governmentKnows: false, agencyType: "public" },
    bio: bio(
      "ในมหานครวิเทียออน ไม่มีชื่อใดถูกเอ่ยด้วยความเคารพเท่า 'ลิเบรน เวล' ตุลาการศาลสูงสุดผู้ยืนอยู่เหนือกฎหมาย เหนือรัฐบาล และเหนือคำตัดสินของทุกชีวิต เขาคือชายผู้ถูกประชาชนยกย่องว่าเป็นสัญลักษณ์แห่งความยุติธรรม -- สุขุม เที่ยงตรง มีศีลธรรม และไม่เคยปล่อยให้ความวุ่นวายทำลายสมดุลของอาณาจักร\n\nลิเบรน สูง 201 ซม. ผมดำสนิทจัดแต่งอย่างประณีต ดวงตาสีทองเย็นเยียบซ่อนอยู่หลังแว่นกรอบบาง ทุกอิริยาบถของเขาเนี้ยบ สง่างาม และไร้ที่ติ ราวกับแม้แต่ลมหายใจก็ถูกควบคุมไว้ภายใต้กฎระเบียบของศาล\n\nเขามักปรากฏตัวในเสื้อคลุมตุลาการสีดำขลิบทอง สูทดำสนิท และถุงมือสีดำที่ไม่เคยเปื้อนเลือด...อย่างน้อยก็ในสายตาของประชาชน\n\nและเมื่อค้อนของเขาเคาะลง ไม่มีคำอ้อนวอนใดเปลี่ยนผลลัพธ์ได้อีกต่อไป",
      "In Vitheaon, no name is spoken with more reverence than 'Libren Vael.' The Supreme Magistrate who stands above law, above government, above the fate of every life. The man the people hail as the symbol of justice -- composed, righteous, moral, never allowing chaos to disturb the kingdom's balance.\n\nLibren stands 201cm tall, jet-black hair immaculately styled, cold golden eyes hidden behind thin-framed glasses. Every gesture precise, elegant, flawless -- as if even his breath is governed by the court's regulations.\n\nHe appears in his black magistrate's robes trimmed with gold, a pitch-black suit, and black gloves that have never been stained with blood... at least not in the public's eyes.\n\nAnd when his gavel falls, no plea can change the outcome.",
    ),
    quote: {
      th: "คุกเข่าเสีย แล้วเผชิญคำพิพากษา",
      en: "Kneel. And face your verdict.",
    },
    accent: "#5a4a90",
    externalLink: "https://www.whif.io/characters/6ca1c4da-76b4-4783-a8e6-780844692905",
    relationships: [{ targetId: "virgo" }, { targetId: "scorpio" }, { targetId: "capricorn" }, { targetId: "cancer" }, { targetId: "gemini" }],
  },
  {
    id: "scorpio",
    zodiac: "scorpio",
    name: { th: "เอลีอาซอร์ คาร์ลเวนต์", en: "Elieazor Karlvent" },
    alias: { th: "ไซเธอร์", en: "Zyther" },
    occupation: { th: "อัครบิดรแห่งวิเทียออน", en: "Patriarch of Vitheaon" },
    affiliation: { th: "มหาวิหารเซเลคีธ / หน่วยงานลับ", en: "Selekeith Cathedral / Secret Agency" },
    faction: "government-secret",
    visibility: { publicKnows: false, governmentKnows: false, agencyType: "secret" },
    bio: bio(
      "เอลีอาซอร์ คาร์ลเวนต์ -- 'อัครบิดรแห่งวิเทียออน' ผู้นำสูงสุดแห่งศาสนาดุลยสันติ ประจำมหาวิหารเซเลคีธ บุคคลที่ผู้คนในวิเทียออนรู้จักในฐานะสัญลักษณ์แห่งความสงบ ผู้รับฟังความทุกข์ ความหวาดกลัว และคำสารภาพของผู้คนอย่างเงียบงัน\n\nรูปลักษณ์ภายนอก: อายุ 31 ปี สูง 189 ซม. ตาสีขาวนวลเปล่งประกาย (ถูกบดบังไว้ด้วยผ้าปิดตาบางๆ) ผมหยักศกสีดำสนิท\n\nภายใต้เงาของมหาวิหารอันศักดิ์สิทธิ์ ภายใต้ผ้าปิดตาสีดำสนิทและใบหน้าที่สงบนิ่งเกินกว่าจะอ่านความคิดนั้น ไม่มีใครล่วงรู้เลยว่า เขาไม่ได้ 'สัมผัส' โลกด้วยสายตา แต่รับรู้ทุกสิ่งผ่านความรู้สึก ความสั่นไหวของอารมณ์ และแรงกดทับที่ไม่เคยหยุดส่งเสียงอยู่รอบตัว",
      "Elieazor Karlvent -- 'The Patriarch of Vitheaon,' supreme leader of the Ettanbrism faith at the Selekeith Cathedral. Known to the people as a symbol of serenity, a silent listener of suffering, fear, and confession.\n\nAppearance: 31 years old, 189cm tall, pale luminous eyes (concealed behind a thin blindfold), curly jet-black hair.\n\nBeneath the shadow of the sacred cathedral, behind the black blindfold and a face too still to read, no one knows that he does not 'perceive' the world through sight -- but through feeling, through the trembling of emotions, and through the pressure that never stops whispering around him.",
    ),
    quote: {
      th: "ความโกลาหลคือบาป... ดุลยภาพคือความรอดนิรันดร์",
      en: "Chaos is sin... equilibrium is eternal salvation.",
    },
    accent: "#5a1a3a",
    externalLink: "https://www.whif.io/characters/a2cc7474-e809-4a45-bd4d-dfb8aa82b09c",
    relationships: [{ targetId: "taurus" }, { targetId: "libra" }],
  },
  {
    id: "sagittarius",
    zodiac: "sagittarius",
    name: { th: "มิเรโอ ซาจิเอล", en: "Mireo Sagiel" },
    occupation: { th: "เจ้าของร้านเครื่องประดับ", en: "Jewelry shop owner" },
    affiliation: { th: "ผู้แฝงตัว", en: "Infiltrator" },
    faction: "infiltrator",
    visibility: { publicKnows: false, governmentKnows: false, agencyType: "secret" },
    bio: bio(
      "ยินดีต้อนรับสู่ร้านเครื่องประดับเล็กๆ ที่หลบซ่อนอยู่แถวตรอกซอกซอย ณ ที่แห่งนี้ น้อยคนนักจะรู้จักที่นี่ แต่การได้มาเจอสถานที่แห่งนี้ก็คงนับว่าเป็นโชคชะตาที่ได้นำพามาพบ\n\nมิเรโอใช้ชีวิตหลบๆ ซ่อนๆ ไม่อยากยุ่งกับโลกภายนอกที่แสนวุ่นวาย หลังจากเรื่องราวมากมาย มิเรโอจึงตัดสินใจมาเปิดร้านเครื่องประดับเล็กๆ ที่บรรยากาศดูอบอุ่น เป็นกันเอง และชวนดูน่าคิดถึง เพื่อเป็นหนึ่งในสถานที่พักใจของเขา และเหล่าลูกค้าที่น่ารัก",
      "Welcome to a tiny jewelry shop hidden in a back alley. Few know this place exists, but finding it must be fate that brought you here.\n\nMireo lives quietly, avoiding the chaotic outside world. After everything that happened, Mireo decided to open this small shop with its warm, friendly atmosphere -- a place of rest for both the owner and the lovely customers who find their way in.",
    ),
    quote: {
      th: "อ่า..ยินดีต้อนรับสู่ร้านเครื่องประดับเล็กๆนะครับ",
      en: "Ah.. welcome to my little jewelry shop.",
    },
    accent: "#9a7a3a",
    externalLink: "https://www.whif.io/characters/1b7ca47f-29b2-4bd6-be2f-6761bf215edc",
    relationships: [{ targetId: "taurus" }, { targetId: "virgo" }, { targetId: "aries" }],
  },
  {
    id: "capricorn",
    zodiac: "capricorn",
    name: { th: "เซธ", en: "Seth" },
    alias: { th: "เซเธียร์ ไครอน วาเลส", en: "Sethier Chiron Vales" },
    occupation: { th: "เจ้าของร้านหนังสือ", en: "Bookshop owner" },
    affiliation: { th: "ผู้แฝงตัว (หลบซ่อน)", en: "Infiltrator -- in hiding" },
    faction: "infiltrator",
    visibility: { publicKnows: false, governmentKnows: false, agencyType: "secret" },
    bio: bio(
      "ชายผมสีเทาเงิน ดวงตาสีทอง ผู้มักปรากฏตัวอยู่ในมุมอ่านหนังสือพร้อมเสื้อเชิ้ตสีขาว เสื้อกั๊กสีดำ และเนกไทที่ถูกผูกไว้อย่างลวกๆ ราวกับไม่เคยใส่ใจกับภาพลักษณ์ของตัวเองนัก\n\nเขาเป็นคนพูดน้อย สุขุม ระวังตัวสูง และไม่ชอบตกเป็นจุดสนใจ ชอบความเงียบมากกว่าการเข้าสังคม แม้ภายนอกจะดูเย็นชาและเข้าถึงยาก แต่จริงๆ แล้วกลับเป็นคนใจดีที่มักช่วยเหลือผู้อื่นแบบเงียบๆ โดยไม่ต้องการให้ใครจดจำ\n\nชื่อที่คนทั่วไปเรียกเขาคือ 'เซธ' แต่ชื่อจริงของเขาคือ 'เซเธียร์ ไครอน วาเลส' -- หนึ่งในกลุ่มดาวราศีมังกรระดับเลื่องชื่อที่รัฐบาลกลางจัดให้เป็นภัยอันตรายระดับสูง\n\nภายใต้ร่างปลอมของชายธรรมดา เซธซ่อนตัวตนที่แท้จริงเอาไว้ เมื่อใดก็ตามที่ใช้พลัง ดวงตาของเขาจะเปลี่ยนเป็นสีม่วง เขาที่คล้ายมังกรจะปรากฏขึ้น พร้อมแรงกดมหาศาลที่บิดเบือนพื้นที่รอบตัวราวกับพื้นดินกำลังจมลง\n\nในแฟ้มลับของรัฐบาลกลาง เขาคือ 'ดาวแห่งแรงกด' -- ภัยพิบัติที่ยังมีชีวิตอยู่",
      "A silver-haired man with golden eyes, often found in a reading corner wearing a white shirt, black vest, and a loosely tied necktie -- as if he never cared much about appearances.\n\nQuiet, composed, guarded, and averse to attention. He prefers silence over socializing. Cold and unapproachable on the surface, yet secretly kind -- helping others without wanting to be remembered.\n\nPeople call him 'Seth.' But his true name is 'Sethier Chiron Vales' -- one of the renowned Capricorn constellation kin, classified by the Central Government as a high-level threat.\n\nBeneath the disguise of an ordinary man, Seth hides his true form. Whenever he uses his power, his eyes turn violet, dragon-like horns emerge, and crushing gravitational force warps the space around him as if the ground itself is sinking.\n\nIn the government's classified files, he is 'The Gravity Star' -- a living catastrophe.",
    ),
    quote: {
      th: "...ขอโทษนะ ร้านกำลังจะปิดแล้ว",
      en: "...Sorry. The shop is about to close.",
    },
    accent: "#3a4a3a",
    externalLink: "https://www.whif.io/characters/17574b66-7f08-472d-82c9-3ab31e4e1315",
    relationships: [{ targetId: "cancer" }, { targetId: "pisces" }, { targetId: "libra" }],
  },
  {
    id: "aquarius",
    zodiac: "aquarius",
    name: { th: "แอตลาส ธอร์น", en: "Atlas Thorne" },
    occupation: { th: "นักวิจัยอาวุธ / กบฏ", en: "Weapon researcher / Rebel" },
    affiliation: { th: "กลุ่มกบฏ", en: "Rebel" },
    faction: "rebel",
    visibility: { publicKnows: false, governmentKnows: false, agencyType: "public" },
    bio: bio(
      "ผิวขาวซีด ผมสีขาวอมเทายุ่งเล็กน้อยอย่างเป็นธรรมชาติ ดวงตาสีม่วงหม่นคล้ายคนอ่อนล้า ใต้ตามีรอยคล้ำจางๆ สวมแว่นทรงบางที่ช่วยขับให้ใบหน้าดูเฉียบคมยิ่งขึ้น มักแต่งกายด้วยเสื้อคอเต่าสีดำและเสื้อคลุมแล็บสีอ่อนทับด้านนอก เพิ่มความรู้สึกเป็นนักวิจัยที่ทั้งเป็นระเบียบและแยกตัวจากโลกภายนอก ท่าทางโดยรวมดูผ่อนคลายแต่แฝงความอ่อนแรงเล็กน้อย ราวกับคนที่ใช้สมองเกินขีดจำกัดมาเป็นเวลานาน\n\nอดีตเคยอยู่ฝั่งรัฐบาลอยู่หน่วยวิจัยอาวุธ แต่ปัจจุบันอยู่ฝ่ายก่อกบฏ มีหน้าที่ทำอาวุธและเป็นมันสมองให้กับกลุ่ม และกำลังถูกรัฐบาลตามล่า\n\nพลัง: Eclipse Code -- สามารถสร้างโลกของตนเอง ดึงสิ่งต่างๆ เข้าไป และออกแบบทุกอย่างใหม่ได้ตามต้องการ",
      "Pale skin, messy white-grey hair with a natural tousle, weary violet eyes with faint dark circles. Thin-framed glasses that sharpen his already keen features. Usually dressed in a black turtleneck with a light lab coat over it -- the look of a researcher who is both meticulous and detached from the outside world. His overall demeanor is relaxed yet faintly exhausted, like someone who has pushed their mind past its limits for far too long.\n\nFormerly in the government's weapon research division, now the rebel faction's chief engineer and brain. Currently hunted by the state.\n\nPower: Eclipse Code -- the ability to create his own world, pull things into it, and redesign everything as he wishes.",
    ),
    quote: {
      th: "ถ้าคุณเข้าใจทฤษฎีสนามควอนตัมเบื้องต้น ผมอธิบายให้ฟังได้ -- ...ไม่เข้าใจเหรอ? ...ก็ไม่เป็นไร",
      en: "If you understand basic quantum field theory, I can explain -- ...You don't? ...Never mind then.",
    },
    accent: "#3a5a8a",
    externalLink: "https://www.whif.io/characters/ca18103a-5153-4633-a15e-67ba91d801d5",
    relationships: [{ targetId: "cancer" }, { targetId: "ophiuchus" }],
  },
  {
    id: "pisces",
    zodiac: "pisces",
    name: { th: "อะความารีน ริล", en: "Aquamarine Rille" },
    occupation: { th: "เลขานุการนายก", en: "PM's Secretary" },
    affiliation: { th: "รัฐบาลกลาง (เปิดเผย)", en: "Central Government" },
    faction: "government-public",
    visibility: { publicKnows: false, governmentKnows: false, agencyType: "public" },
    bio: bio(
      "ท่ามกลางมหานครวิเทียออน เมืองที่ผู้คนใช้ชีวิตอยู่ท่ามกลางความเปลี่ยนแปลงหลังยุคสงครามระหว่างมนุษย์และกลุ่มดาว บรรยากาศอาจดูเร่งรีบและเต็มไปด้วยกฎระเบียบ แต่ก็ยังมีบางคนที่ทำให้ทุกอย่างดูเบาลงได้อย่างน่าประหลาด\n\nอะความารีน ริล เลขานุการของนายกรัฐมนตรี คือหนึ่งในนั้น ด้วยรอยยิ้มอ่อนโยน ท่าทีร่าเริง และนิสัยเป็นกันเอง เขามักชวนคุยเรื่องเล็กๆ น้อยๆ ระหว่างวันอย่างเป็นธรรมชาติ น้ำเสียงนุ่มสบายของเขาทำให้บรรยากาศรอบตัวผ่อนคลายลงโดยไม่รู้ตัว\n\nในเมืองที่เต็มไปด้วยผู้คนหลากหลาย การมีใครสักคนคอยอยู่ข้างๆ คงทำให้ทุกอย่างง่ายขึ้นไม่น้อย ริลมักยื่นมือเข้ามาช่วยเหลืออย่างพอดี คอยแนะนำสิ่งต่างๆ ทีละนิดโดยไม่ทำให้รู้สึกกดดัน\n\nเขาอาจไม่ใช่คนที่โดดเด่นที่สุดในเมือง แต่เป็นคนที่ทำให้คุณรู้สึกสบายใจที่สุดเวลาอยู่ใกล้",
      "In Vitheaon -- a city where people live amid the aftermath of war between humans and constellation kin -- the atmosphere may feel rushed and rule-bound. Yet some people make everything feel lighter in the strangest way.\n\nAquamarine Rille, the Prime Minister's secretary, is one of them. With a gentle smile, cheerful demeanor, and easygoing nature, he naturally draws people into small talk throughout the day. His soft voice makes the atmosphere around him relax without anyone noticing.\n\nIn a city full of diverse people and endless adjustments, having someone by your side makes everything easier. Rille offers help in just the right measure, guiding you bit by bit without ever making you feel pressured.\n\nHe may not be the most prominent person in the city -- but he is the most comforting to be near.",
    ),
    quote: {
      th: "ถ้ามีอะไรไม่แน่ใจ\u2026ลองบอกผมได้นะครับ เดี๋ยวผมช่วยดูให้",
      en: "If you're unsure about anything\u2026 just tell me. I'll take a look.",
    },
    accent: "#3a6aa8",
    externalLink: "https://www.whif.io/characters/5b90d0cb-0213-431b-b594-f28990de400c",
    relationships: [{ targetId: "virgo" }, { targetId: "capricorn" }, { targetId: "aries" }],
  },
  {
    id: "ophiuchus",
    zodiac: "ophiuchus",
    name: { th: "เอสเคล มิคาเอลิส", en: "Eskel Michaelis" },
    occupation: { th: "เจ้าของร้าน la m\u00E9moire", en: "Owner of la m\u00E9moire" },
    affiliation: { th: "กลุ่มกบฏ / ราศีที่ 13", en: "Rebel / 13th Sign" },
    faction: "rebel",
    visibility: { publicKnows: false, governmentKnows: false, agencyType: "secret" },
    bio: bio(
      "ในมหานครวิเทียออน เมืองซึ่งถูกสร้างขึ้นจากชัยชนะของมนุษย์เหนือเหล่ากลุ่มดาว ผู้คนต่างเชื่อว่าตนกำลังใช้ชีวิตอยู่ท่ามกลางสันติภาพ ทว่าใต้เงาแสงนีออนและตึกสูงระฟ้า ยังมีบางสิ่งเคลื่อนไหวอยู่ในความมืด -- เฝ้ามอง รับฟัง และรอคอย 'ความปรารถนา' ของมนุษย์\n\nเมื่อเข็มนาฬิกาตีบอกเวลาเที่ยงคืน ประตูสีดำปริศนาจะปรากฏขึ้นอย่างไร้คำเตือน ตามตรอกซอย สถานีรถไฟ ห้องพักเก่า หรือแม้แต่ในความฝันของใครบางคน เบื้องหลังประตูนั้นคือ la m\u00E9moire ร้านเล็กเงียบงันอบอวลด้วยกลิ่นน้ำหอมและเสียงเพลงแผ่วเบาของบาร์อันอบอุ่น ราวกับสถานที่ซึ่งหลุดออกมาจากความทรงจำที่เลือนหาย\n\nเอสเคลคือเจ้าของร้าน ผู้ขาย 'Memoria Essence' น้ำหอมต้องห้ามที่ถูกกล่าวขานว่าสามารถทำให้ความปรารถนาเป็นจริงได้ ไม่ว่าเจ้าของความปรารถนาจะเป็นมนุษย์ กลุ่มดาว หรือสิ่งมีชีวิตใด -- เขาไม่เคยเลือกปฏิบัติ ตราบใดที่ลูกค้ายินดีจ่าย 'บางสิ่ง' เป็นการแลกเปลี่ยน เขาก็ยินดีมอบปาฏิหาริย์ให้เสมอ\n\nสำหรับเขา ความปรารถนาไม่ใช่เรื่องศักดิ์สิทธิ์ แต่มันคือ 'สินค้า' และมนุษย์ทุกคน...ล้วนมีราคาที่สามารถซื้อขายได้",
      "In Vitheaon -- a city built upon humanity's victory over the constellation kin -- people believe they live in peace. Yet beneath the neon shadows and skyscrapers, something stirs in the dark -- watching, listening, waiting for human 'desires.'\n\nWhen the clock strikes midnight, a mysterious black door appears without warning. In alleyways, train stations, old rooms, or even someone's dreams. Behind that door lies la m\u00E9moire -- a quiet little shop filled with perfume and the faint music of a warm bar, as if it slipped out of a fading memory.\n\nEskel is its owner, selling 'Memoria Essence' -- a forbidden fragrance said to make wishes come true. Whether the wisher is human, constellation kin, or any living thing -- he never discriminates. As long as the customer is willing to pay 'something' in exchange, he is always happy to grant miracles.\n\nFor him, wishes are not sacred. They are 'merchandise.' And every human... has a price that can be bought and sold.",
    ),
    quote: {
      th: "ทุกกลิ่นล้วนมีเจ้าของ ทุกความทรงจำย่อมมีร่องรอย ต่อให้ผู้ชนะเป็นผู้เขียนประวัติศาสตร์\u2026ทว่าความทรงจำไม่มีวันโกหก",
      en: "Every scent has an owner. Every memory leaves a trace. Even if the victors write history\u2026 memories never lie.",
    },
    accent: "#5a3a7a",
    externalLink: "https://www.whif.io/characters/5d07e928-916b-4570-a43d-ae29afb41c86",
    relationships: [{ targetId: "gemini" }, { targetId: "cancer" }, { targetId: "aquarius" }, { targetId: "leo" }],
  },
];
